from django.conf.urls import *

urlpatterns = patterns('',
    (r'^getAccessToken$', 'socialplatform.views.getAccessToken'),
    (r'^connect$', 'socialplatform.views.facebookConnect'),
    (r'^notifications_test/([A-Za-z0-9_\.-]+)$', 'socialplatform.views.sendTestNotification'),
    (r'^getAppAccess/([A-Za-z0-9_\.-]+)$', 'socialplatform.views.getAppAccessToken'),
    # (r'^updateToken/([A-Za-z0-9_\.-]+)$', 'socialplatform.views.updateToken'),
    (r'^broadcastNotification/([A-Za-z0-9_\.-]+)$', 'socialplatform.views.access_for_broadcast'),
    (r'^broadcast/([A-Za-z0-9_\.-]+)$', 'socialplatform.views.social_broadcast'),
    (r'^add_account', 'socialplatform.views.add_twitter_acct'),
    (r'^deactivate', 'socialplatform.views.remove_twitter_acct'),
    (r'^helpbroadcast/([A-Za-z0-9_\.-]+)$', 'socialplatform.views.broadcast_help'),
    (r'^helpnotify/([A-Za-z0-9_\.-]+)$', 'socialplatform.views.sending_help'),
    (r'^issuenotify/([A-Za-z0-9_\.-]+)$', 'socialplatform.views.notify_assignment'),
    (r'^assignbroadcast/([A-Za-z0-9_\.-]+)$', 'socialplatform.views.assignment_broadcast'),
    (r'^notifypoll/([A-Za-z0-9_\.-]+)$', 'socialplatform.views.notify_new_poll'),
    (r'^newpollbroadcast/([A-Za-z0-9_\.-]+)$', 'socialplatform.views.new_poll_broadcast'),
    (r'^modify_permission$', 'socialplatform.views.modify_permissions'),
)